name: Publish Package
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: 'Publish'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build -- ngx-fluent

      - name: Copy root README file to lib
        run: cp -rf README.md ./dist/ngx-fluent

      - name: Publish to NPM
        run: cd ./dist/ngx-fluent && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
